apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: hello-vienna
  namespace: dev-steve
spec:
  tag: harbor.apps.tapmc.v2steve.net/demosteveschmidt/hello-vienna
  serviceAccountName: harbor-service-account
  builder:
    name: ws-builder
    kind: Builder
  source:
    git:
      url: https://github.com/demosteveschmidt/hello-vienna
      revision: main
